import type { ConversationScenario } from "./types";

export const DEFAULT_SCENARIOS: ConversationScenario[] = [
  {
    id: "office-meeting",
    title: "Office Meeting",
    titleCn: "办公室会议",
    description: "Practice scheduling and discussing meetings with colleagues",
    context: "You are in an office setting. A colleague wants to schedule a meeting about a project.",
    difficulty: 1,
    category: "office",
  },
  {
    id: "restaurant-order",
    title: "Restaurant Order",
    titleCn: "餐厅点餐",
    description: "Practice ordering food and asking about menu items",
    context: "You are at a restaurant during a business lunch and need to order politely.",
    difficulty: 1,
    category: "restaurant",
  },
  {
    id: "airport-checkin",
    title: "Airport Check-in",
    titleCn: "机场值机",
    description: "Practice check-in, baggage, and flight questions",
    context: "You are at an airport check-in counter for a business trip.",
    difficulty: 2,
    category: "airport",
  },
  {
    id: "hotel-reservation",
    title: "Hotel Reservation",
    titleCn: "酒店预订",
    description: "Practice reservation changes and hotel requests",
    context: "You are calling a hotel to book or modify a reservation.",
    difficulty: 2,
    category: "hotel",
  },
  {
    id: "phone-inquiry",
    title: "Phone Inquiry",
    titleCn: "电话咨询",
    description: "Practice business phone inquiry and message leaving",
    context: "You are calling a company to ask for service details.",
    difficulty: 2,
    category: "phone",
  },
  {
    id: "job-interview",
    title: "Job Interview",
    titleCn: "工作面试",
    description: "Practice interview answers with clearer structure",
    context: "You are attending an interview at an international company.",
    difficulty: 3,
    category: "interview",
  },
  {
    id: "product-presentation",
    title: "Product Presentation",
    titleCn: "产品介绍",
    description: "Practice presenting value proposition to clients",
    context: "You are presenting a new product to potential business partners.",
    difficulty: 3,
    category: "meeting",
  },
  {
    id: "complaint-resolution",
    title: "Customer Complaint",
    titleCn: "客户投诉",
    description: "Practice handling complaints with professional tone",
    context: "A customer reports a delayed shipment and expects a solution.",
    difficulty: 3,
    category: "phone",
  },
];
