import type { ConversationScenario } from "./types";

export const DEFAULT_SCENARIOS: ConversationScenario[] = [
  {
    id: "office-meeting",
    title: "Office Meeting",
    titleCn: "办公室会议",
    description: "Practice scheduling and discussing meetings with colleagues",
    context: "You are in an office setting. A colleague wants to schedule a meeting about a project.",
    targetLanguage: "en",
    difficulty: 1,
    category: "office",
  },
  {
    id: "restaurant-order",
    title: "Restaurant Order",
    titleCn: "餐厅点餐",
    description: "Practice ordering food and asking about menu items",
    context: "You are at a restaurant during a business lunch and need to order politely.",
    targetLanguage: "en",
    difficulty: 1,
    category: "restaurant",
  },
  {
    id: "airport-checkin",
    title: "Airport Check-in",
    titleCn: "机场值机",
    description: "Practice check-in, baggage, and flight questions",
    context: "You are at an airport check-in counter for a business trip.",
    targetLanguage: "en",
    difficulty: 2,
    category: "airport",
  },
  {
    id: "hotel-reservation",
    title: "Hotel Reservation",
    titleCn: "酒店预订",
    description: "Practice reservation changes and hotel requests",
    context: "You are calling a hotel to book or modify a reservation.",
    targetLanguage: "en",
    difficulty: 2,
    category: "hotel",
  },
  {
    id: "phone-inquiry",
    title: "Phone Inquiry",
    titleCn: "电话咨询",
    description: "Practice business phone inquiry and message leaving",
    context: "You are calling a company to ask for service details.",
    targetLanguage: "en",
    difficulty: 2,
    category: "phone",
  },
  {
    id: "job-interview",
    title: "Job Interview",
    titleCn: "工作面试",
    description: "Practice interview answers with clearer structure",
    context: "You are attending an interview at an international company.",
    targetLanguage: "en",
    difficulty: 3,
    category: "interview",
  },
  {
    id: "product-presentation",
    title: "Product Presentation",
    titleCn: "产品介绍",
    description: "Practice presenting value proposition to clients",
    context: "You are presenting a new product to potential business partners.",
    targetLanguage: "en",
    difficulty: 3,
    category: "meeting",
  },
  {
    id: "complaint-resolution",
    title: "Customer Complaint",
    titleCn: "客户投诉",
    description: "Practice handling complaints with professional tone",
    context: "A customer reports a delayed shipment and expects a solution.",
    targetLanguage: "en",
    difficulty: 3,
    category: "phone",
  },
  {
    id: "ja-convenience-store",
    title: "コンビニで買い物",
    titleCn: "便利店购物",
    description: "店員に商品や支払い方法を尋ねる練習",
    context: "あなたはコンビニで買い物をしています。探している商品と支払い方法について日本語で店員に尋ねてください。",
    targetLanguage: "ja",
    difficulty: 1,
    category: "shopping",
  },
  {
    id: "ja-restaurant-order",
    title: "レストランで注文",
    titleCn: "日式餐厅点餐",
    description: "料理を注文し、店員におすすめを聞く練習",
    context: "あなたは日本のレストランにいます。食べたい料理やおすすめを日本語で丁寧に尋ねてください。",
    targetLanguage: "ja",
    difficulty: 1,
    category: "restaurant",
  },
  {
    id: "ja-hotel-checkin",
    title: "ホテルでチェックイン",
    titleCn: "酒店办理入住",
    description: "予約確認とチェックインのやり取りを練習",
    context: "あなたはホテルのフロントにいます。予約名を伝え、チェックインについて日本語でやり取りしてください。",
    targetLanguage: "ja",
    difficulty: 2,
    category: "hotel",
  },
  {
    id: "ja-part-time-interview",
    title: "アルバイト面接",
    titleCn: "兼职面试",
    description: "志望理由や経験を丁寧に答える練習",
    context: "あなたはアルバイトの面接を受けています。志望理由とこれまでの経験を日本語で簡潔に説明してください。",
    targetLanguage: "ja",
    difficulty: 3,
    category: "interview",
  },
];
